name: Compress Lottie Files
on:
  pull_request:
    paths:
      - '**.json'

jobs:
  compress-lottie:
    name: Compress Lottie JSON Files
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Ensure jq is installed
      - name: Install jq
        run: sudo apt-get install jq

      - name: Run pwd
        run: pwd

      # Run the compression script for files in the commit range
      - name: Compress Changed Lottie Files
        run: |
          chmod +x ./compress_lottie.sh
          ./compress_lottie.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
